# Development container for the SAVRASCA tool
# https://github.com/nikita-veshchikov/savrasca

# Default configs:
# - OS: Arch Linux
# - Package manager: pacman
# - Shell: bash

FROM archlinux:latest
ENV WORKDIR=/home/vscode

RUN pacman -Sy --noconfirm
RUN pacman -S --needed --noconfirm zsh git sudo gcc automake libtool autoconf texinfo make avr-gcc avr-libc avrdude make python avr-gdb

RUN useradd -m vscode -d ${WORKDIR}
# RUN chsh -s /bin/zsh vscode
RUN passwd -d vscode
RUN printf "vscode ALL=(ALL) ALL" >> /etc/sudoers

WORKDIR ${WORKDIR}
USER vscode
RUN git clone https://aur.archlinux.org/yay.git; cd yay; makepkg -si --noconfirm; cd ${WORKDIR}
RUN git clone https://github.com/patricab/savrasca
RUN cd savrasca/simulavr; \ 
git pull; \
autoreconf --install && \
./configure && \
make && make check && sudo make install
WORKDIR ${WORKDIR}/app

COPY .gdbinit ${WORKDIR}/.gdbinit

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>


